# Generated by Django 3.0.6 on 2020-05-28 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('gyear', models.IntegerField()),
                ('ggirlnum', models.IntegerField()),
                ('gboynum', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('sid', models.IntegerField()),
                ('sdate', models.DateField()),
                ('sname', models.CharField()),
                ('scity', models.CharField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('xid', models.IntegerField()),
                ('xname', models.CharField()),
                ('xage', models.IntegerField()),
                ('xgender', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
                ('xgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boy.Grades')),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=10)),
                ('pp_start_time', models.DateField()),
                ('pp_long', models.IntegerField()),
                ('pstart_time', models.DateField()),
                ('pover_time', models.DateField()),
                ('plong', models.IntegerField()),
                ('pscore', models.IntegerField()),
                ('pstudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boy.Students')),
            ],
        ),
        migrations.AddField(
            model_name='grades',
            name='gschool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boy.Schools'),
            #(model_name='students',
           # name='gschool',
            #field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boy.Schools')
        ),
    ]
