# Generated by Django 3.0.6 on 2020-05-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boy', '0001_initial'),
    ]

    operations = [
    ]
